[2023-09-14T14:30:55.115+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-10T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-14T14:30:55.116+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-10T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-10T00:00:00+00:00/task_id=insert_into_table'
[2023-09-14T14:30:55.171+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-10T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-14T14:30:55.173+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-10T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-10T00:00:00+00:00/task_id=insert_into_table'
[2023-09-14T14:30:55.247+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-10T00:00:00+00:00 [queued]>
[2023-09-14T14:30:55.269+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-10T00:00:00+00:00 [queued]>
[2023-09-14T14:30:55.270+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-14T14:30:55.299+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2023-09-10 00:00:00+00:00
[2023-09-14T14:30:55.309+0000] {standard_task_runner.py:57} INFO - Started process 196 to run task
[2023-09-14T14:30:55.314+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'insert_into_table', 'scheduled__2023-09-10T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/dag-postgres-operator.py', '--cfg-path', '/tmp/tmpgnx6idq6']
[2023-09-14T14:30:55.318+0000] {standard_task_runner.py:85} INFO - Job 105: Subtask insert_into_table
[2023-09-14T14:30:55.398+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-10T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-14T14:30:55.400+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-10T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-10T00:00:00+00:00/task_id=insert_into_table'
[2023-09-14T14:30:55.405+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-10T00:00:00+00:00 [running]> on host 6c82fec646db
[2023-09-14T14:30:55.548+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='qpsss' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v02' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2023-09-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-10T00:00:00+00:00'
[2023-09-14T14:30:55.550+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2023-09-10', 'dag_with_postgres_operator_v02')
        
[2023-09-14T14:30:55.565+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-14T14:30:55.581+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-14T14:30:55.587+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2023-09-10', 'dag_with_postgres_operator_v02')
        , parameters: None
[2023-09-14T14:30:55.595+0000] {sql.py:427} INFO - Rows affected: 1
[2023-09-14T14:30:55.612+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v02, task_id=insert_into_table, execution_date=20230910T000000, start_date=20230914T143055, end_date=20230914T143055
[2023-09-14T14:30:55.648+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-14T14:30:55.675+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
