[2023-09-16T07:59:30.907+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-15T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-16T07:59:30.908+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-15T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-15T00:00:00+00:00/task_id=insert_into_table'
[2023-09-16T07:59:30.955+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-15T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-16T07:59:30.958+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-15T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-15T00:00:00+00:00/task_id=insert_into_table'
[2023-09-16T07:59:31.024+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-15T00:00:00+00:00 [queued]>
[2023-09-16T07:59:31.042+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-15T00:00:00+00:00 [queued]>
[2023-09-16T07:59:31.044+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-16T07:59:31.068+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2023-09-15 00:00:00+00:00
[2023-09-16T07:59:31.078+0000] {standard_task_runner.py:57} INFO - Started process 188 to run task
[2023-09-16T07:59:31.082+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'insert_into_table', 'scheduled__2023-09-15T00:00:00+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/dag-postgres-operator.py', '--cfg-path', '/tmp/tmpojogmyz9']
[2023-09-16T07:59:31.086+0000] {standard_task_runner.py:85} INFO - Job 115: Subtask insert_into_table
[2023-09-16T07:59:31.178+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-15T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-16T07:59:31.181+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-15T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-15T00:00:00+00:00/task_id=insert_into_table'
[2023-09-16T07:59:31.188+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-15T00:00:00+00:00 [running]> on host 6c82fec646db
[2023-09-16T07:59:31.411+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='qpsss' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v02' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2023-09-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-15T00:00:00+00:00'
[2023-09-16T07:59:31.414+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2023-09-15', 'dag_with_postgres_operator_v02')
        
[2023-09-16T07:59:31.429+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-16T07:59:31.445+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-16T07:59:31.453+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2023-09-15', 'dag_with_postgres_operator_v02')
        , parameters: None
[2023-09-16T07:59:31.456+0000] {sql.py:427} INFO - Rows affected: 1
[2023-09-16T07:59:31.479+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v02, task_id=insert_into_table, execution_date=20230915T000000, start_date=20230916T075931, end_date=20230916T075931
[2023-09-16T07:59:31.538+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-16T07:59:31.562+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
