[2023-09-24T11:04:45.715+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-17T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-24T11:04:45.718+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-17T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-17T00:00:00+00:00/task_id=insert_into_table'
[2023-09-24T11:04:45.907+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-17T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-24T11:04:45.911+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-17T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-17T00:00:00+00:00/task_id=insert_into_table'
[2023-09-24T11:04:46.084+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-17T00:00:00+00:00 [queued]>
[2023-09-24T11:04:46.140+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-17T00:00:00+00:00 [queued]>
[2023-09-24T11:04:46.143+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-24T11:04:46.218+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2023-09-17 00:00:00+00:00
[2023-09-24T11:04:46.244+0000] {standard_task_runner.py:57} INFO - Started process 206 to run task
[2023-09-24T11:04:46.259+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'insert_into_table', 'scheduled__2023-09-17T00:00:00+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/dag-postgres-operator.py', '--cfg-path', '/tmp/tmp2ng5s0gt']
[2023-09-24T11:04:46.272+0000] {standard_task_runner.py:85} INFO - Job 128: Subtask insert_into_table
[2023-09-24T11:04:46.500+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-17T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-24T11:04:46.503+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-17T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-17T00:00:00+00:00/task_id=insert_into_table'
[2023-09-24T11:04:46.510+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-17T00:00:00+00:00 [running]> on host 6c82fec646db
[2023-09-24T11:04:47.105+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='qpsss' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v02' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2023-09-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-17T00:00:00+00:00'
[2023-09-24T11:04:47.112+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2023-09-17', 'dag_with_postgres_operator_v02')
        
[2023-09-24T11:04:47.163+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-24T11:04:47.220+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-24T11:04:47.268+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2023-09-17', 'dag_with_postgres_operator_v02')
        , parameters: None
[2023-09-24T11:04:47.302+0000] {sql.py:427} INFO - Rows affected: 1
[2023-09-24T11:04:47.373+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v02, task_id=insert_into_table, execution_date=20230917T000000, start_date=20230924T110446, end_date=20230924T110447
[2023-09-24T11:04:47.755+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-24T11:04:47.820+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
