[2023-09-02T08:51:49.098+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=manual__2023-09-02T08:45:59.622351+00:00/task_id=insert_into_table permission to 509
[2023-09-02T08:51:49.100+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=manual__2023-09-02T08:45:59.622351+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=manual__2023-09-02T08:45:59.622351+00:00/task_id=insert_into_table'
[2023-09-02T08:51:49.130+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=manual__2023-09-02T08:45:59.622351+00:00/task_id=insert_into_table permission to 509
[2023-09-02T08:51:49.131+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=manual__2023-09-02T08:45:59.622351+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=manual__2023-09-02T08:45:59.622351+00:00/task_id=insert_into_table'
[2023-09-02T08:51:49.176+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_table manual__2023-09-02T08:45:59.622351+00:00 [queued]>
[2023-09-02T08:51:49.191+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_table manual__2023-09-02T08:45:59.622351+00:00 [queued]>
[2023-09-02T08:51:49.192+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 9
[2023-09-02T08:51:49.210+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2023-09-02 08:45:59.622351+00:00
[2023-09-02T08:51:49.216+0000] {standard_task_runner.py:57} INFO - Started process 771 to run task
[2023-09-02T08:51:49.218+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'insert_into_table', 'manual__2023-09-02T08:45:59.622351+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/dag-postgres-operator.py', '--cfg-path', '/tmp/tmp2ps4sv4z']
[2023-09-02T08:51:49.221+0000] {standard_task_runner.py:85} INFO - Job 69: Subtask insert_into_table
[2023-09-02T08:51:49.272+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=manual__2023-09-02T08:45:59.622351+00:00/task_id=insert_into_table permission to 509
[2023-09-02T08:51:49.273+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=manual__2023-09-02T08:45:59.622351+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=manual__2023-09-02T08:45:59.622351+00:00/task_id=insert_into_table'
[2023-09-02T08:51:49.276+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.insert_into_table manual__2023-09-02T08:45:59.622351+00:00 [running]> on host 6c82fec646db
[2023-09-02T08:51:49.363+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='qpsss' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v02' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2023-09-02T08:45:59.622351+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-02T08:45:59.622351+00:00'
[2023-09-02T08:51:49.365+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2023-09-02', 'dag_with_postgres_operator_v02')
        
[2023-09-02T08:51:49.375+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-02T08:51:49.386+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-02T08:51:49.391+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2023-09-02', 'dag_with_postgres_operator_v02')
        , parameters: None
[2023-09-02T08:51:49.394+0000] {sql.py:427} INFO - Rows affected: 1
[2023-09-02T08:51:49.409+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v02, task_id=insert_into_table, execution_date=20230902T084559, start_date=20230902T085149, end_date=20230902T085149
[2023-09-02T08:51:49.433+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-02T08:51:49.450+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
